from typing import Protocol, Any, Iterable


class TransactionProtocol(Protocol):
    def fetch_one(self, query: str, params: Iterable[Any]): ...
    def fetch_all(self, query: str, params: Iterable[Any]): ...
    def execute(self, query: str, params: Iterable[Any]): ...


class DatabaseProtocol(Protocol):
    def transaction(self): ...
